//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbxdata.web.ProductReport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/ServiceForProduct/", ConfigurationName="ProductReport.ServiceForProduct")]
    public interface ServiceForProduct {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForProduct/createProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pbxdata.web.ProductReport.createProductResponse createProduct(pbxdata.web.ProductReport.createProductRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForProduct/createProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<pbxdata.web.ProductReport.createProductResponse> createProductAsync(pbxdata.web.ProductReport.createProductRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForProduct/getProduct", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pbxdata.web.ProductReport.getProductResponse getProduct(pbxdata.web.ProductReport.getProductRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForProduct/getProduct", ReplyAction="*")]
        System.Threading.Tasks.Task<pbxdata.web.ProductReport.getProductResponse> getProductAsync(pbxdata.web.ProductReport.getProductRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class HeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string appTokenField;
        
        private string appKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("customerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appToken {
            get {
                return this.appTokenField;
            }
            set {
                this.appTokenField = value;
                this.RaisePropertyChanged("appToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class productData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productSkuField;
        
        private string productBarcodeField;
        
        private string productTitleField;
        
        private string productTitleENField;
        
        private string productStatusField;
        
        private string hsCodeField;
        
        private string hsGoodsNameField;
        
        private string currencyCodeField;
        
        private string unitCodeField;
        
        private string unitNameField;
        
        private string productLengthField;
        
        private string productWidthField;
        
        private string productHeightField;
        
        private string productNetWeightField;
        
        private string productWeightField;
        
        private string productDeclaredValueField;
        
        private string productBarcodeTypeField;
        
        private string productCateoryNameField;
        
        private string productAddTimeField;
        
        private string productUpdateTimeField;
        
        private string originCountryField;
        
        private string applyEnterpriseCodeField;
        
        private string applyEnterpriseCodeCIQField;
        
        private string goodTaxCodeField;
        
        private string goodTaxRateField;
        
        private string brandField;
        
        private string productDescriptionField;
        
        private string specificationsAndModelsField;
        
        private string productLinkField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string productSku {
            get {
                return this.productSkuField;
            }
            set {
                this.productSkuField = value;
                this.RaisePropertyChanged("productSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string productBarcode {
            get {
                return this.productBarcodeField;
            }
            set {
                this.productBarcodeField = value;
                this.RaisePropertyChanged("productBarcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string productTitle {
            get {
                return this.productTitleField;
            }
            set {
                this.productTitleField = value;
                this.RaisePropertyChanged("productTitle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string productTitleEN {
            get {
                return this.productTitleENField;
            }
            set {
                this.productTitleENField = value;
                this.RaisePropertyChanged("productTitleEN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string productStatus {
            get {
                return this.productStatusField;
            }
            set {
                this.productStatusField = value;
                this.RaisePropertyChanged("productStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string hsCode {
            get {
                return this.hsCodeField;
            }
            set {
                this.hsCodeField = value;
                this.RaisePropertyChanged("hsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string hsGoodsName {
            get {
                return this.hsGoodsNameField;
            }
            set {
                this.hsGoodsNameField = value;
                this.RaisePropertyChanged("hsGoodsName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string unitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
                this.RaisePropertyChanged("unitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string unitName {
            get {
                return this.unitNameField;
            }
            set {
                this.unitNameField = value;
                this.RaisePropertyChanged("unitName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string productLength {
            get {
                return this.productLengthField;
            }
            set {
                this.productLengthField = value;
                this.RaisePropertyChanged("productLength");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string productWidth {
            get {
                return this.productWidthField;
            }
            set {
                this.productWidthField = value;
                this.RaisePropertyChanged("productWidth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string productHeight {
            get {
                return this.productHeightField;
            }
            set {
                this.productHeightField = value;
                this.RaisePropertyChanged("productHeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string productNetWeight {
            get {
                return this.productNetWeightField;
            }
            set {
                this.productNetWeightField = value;
                this.RaisePropertyChanged("productNetWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string productWeight {
            get {
                return this.productWeightField;
            }
            set {
                this.productWeightField = value;
                this.RaisePropertyChanged("productWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string productDeclaredValue {
            get {
                return this.productDeclaredValueField;
            }
            set {
                this.productDeclaredValueField = value;
                this.RaisePropertyChanged("productDeclaredValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string productBarcodeType {
            get {
                return this.productBarcodeTypeField;
            }
            set {
                this.productBarcodeTypeField = value;
                this.RaisePropertyChanged("productBarcodeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string productCateoryName {
            get {
                return this.productCateoryNameField;
            }
            set {
                this.productCateoryNameField = value;
                this.RaisePropertyChanged("productCateoryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string productAddTime {
            get {
                return this.productAddTimeField;
            }
            set {
                this.productAddTimeField = value;
                this.RaisePropertyChanged("productAddTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string productUpdateTime {
            get {
                return this.productUpdateTimeField;
            }
            set {
                this.productUpdateTimeField = value;
                this.RaisePropertyChanged("productUpdateTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string originCountry {
            get {
                return this.originCountryField;
            }
            set {
                this.originCountryField = value;
                this.RaisePropertyChanged("originCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string applyEnterpriseCode {
            get {
                return this.applyEnterpriseCodeField;
            }
            set {
                this.applyEnterpriseCodeField = value;
                this.RaisePropertyChanged("applyEnterpriseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string applyEnterpriseCodeCIQ {
            get {
                return this.applyEnterpriseCodeCIQField;
            }
            set {
                this.applyEnterpriseCodeCIQField = value;
                this.RaisePropertyChanged("applyEnterpriseCodeCIQ");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string goodTaxCode {
            get {
                return this.goodTaxCodeField;
            }
            set {
                this.goodTaxCodeField = value;
                this.RaisePropertyChanged("goodTaxCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string goodTaxRate {
            get {
                return this.goodTaxRateField;
            }
            set {
                this.goodTaxRateField = value;
                this.RaisePropertyChanged("goodTaxRate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=25)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=26)]
        public string productDescription {
            get {
                return this.productDescriptionField;
            }
            set {
                this.productDescriptionField = value;
                this.RaisePropertyChanged("productDescription");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=27)]
        public string specificationsAndModels {
            get {
                return this.specificationsAndModelsField;
            }
            set {
                this.specificationsAndModelsField = value;
                this.RaisePropertyChanged("specificationsAndModels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=28)]
        public string productLink {
            get {
                return this.productLinkField;
            }
            set {
                this.productLinkField = value;
                this.RaisePropertyChanged("productLink");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18060")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForProduct/")]
    public partial class ProductInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuNoField;
        
        private string skuNameField;
        
        private string skuEnNameField;
        
        private int skuCategoryField;
        
        private bool skuCategoryFieldSpecified;
        
        private string uOMField;
        
        private int barcodeTypeField;
        
        private bool barcodeTypeFieldSpecified;
        
        private string barcodeDefineField;
        
        private float lengthField;
        
        private bool lengthFieldSpecified;
        
        private float widthField;
        
        private bool widthFieldSpecified;
        
        private float heightField;
        
        private bool heightFieldSpecified;
        
        private float netWeightField;
        
        private float weightField;
        
        private float productDeclaredValueField;
        
        private string productLinkField;
        
        private string hsCodeField;
        
        private string hsGoodsNameField;
        
        private string originCountryField;
        
        private string brandField;
        
        private string specificationsAndModelsField;
        
        private string goodTaxCodeField;
        
        private string applyEnterpriseCodeField;
        
        private string applyEnterpriseCodeCIQField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string skuNo {
            get {
                return this.skuNoField;
            }
            set {
                this.skuNoField = value;
                this.RaisePropertyChanged("skuNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string skuName {
            get {
                return this.skuNameField;
            }
            set {
                this.skuNameField = value;
                this.RaisePropertyChanged("skuName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string skuEnName {
            get {
                return this.skuEnNameField;
            }
            set {
                this.skuEnNameField = value;
                this.RaisePropertyChanged("skuEnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int skuCategory {
            get {
                return this.skuCategoryField;
            }
            set {
                this.skuCategoryField = value;
                this.RaisePropertyChanged("skuCategory");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool skuCategorySpecified {
            get {
                return this.skuCategoryFieldSpecified;
            }
            set {
                this.skuCategoryFieldSpecified = value;
                this.RaisePropertyChanged("skuCategorySpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string UOM {
            get {
                return this.uOMField;
            }
            set {
                this.uOMField = value;
                this.RaisePropertyChanged("UOM");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int barcodeType {
            get {
                return this.barcodeTypeField;
            }
            set {
                this.barcodeTypeField = value;
                this.RaisePropertyChanged("barcodeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool barcodeTypeSpecified {
            get {
                return this.barcodeTypeFieldSpecified;
            }
            set {
                this.barcodeTypeFieldSpecified = value;
                this.RaisePropertyChanged("barcodeTypeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string barcodeDefine {
            get {
                return this.barcodeDefineField;
            }
            set {
                this.barcodeDefineField = value;
                this.RaisePropertyChanged("barcodeDefine");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public float length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lengthSpecified {
            get {
                return this.lengthFieldSpecified;
            }
            set {
                this.lengthFieldSpecified = value;
                this.RaisePropertyChanged("lengthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public float width {
            get {
                return this.widthField;
            }
            set {
                this.widthField = value;
                this.RaisePropertyChanged("width");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool widthSpecified {
            get {
                return this.widthFieldSpecified;
            }
            set {
                this.widthFieldSpecified = value;
                this.RaisePropertyChanged("widthSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public float height {
            get {
                return this.heightField;
            }
            set {
                this.heightField = value;
                this.RaisePropertyChanged("height");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool heightSpecified {
            get {
                return this.heightFieldSpecified;
            }
            set {
                this.heightFieldSpecified = value;
                this.RaisePropertyChanged("heightSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public float netWeight {
            get {
                return this.netWeightField;
            }
            set {
                this.netWeightField = value;
                this.RaisePropertyChanged("netWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public float weight {
            get {
                return this.weightField;
            }
            set {
                this.weightField = value;
                this.RaisePropertyChanged("weight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public float productDeclaredValue {
            get {
                return this.productDeclaredValueField;
            }
            set {
                this.productDeclaredValueField = value;
                this.RaisePropertyChanged("productDeclaredValue");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string productLink {
            get {
                return this.productLinkField;
            }
            set {
                this.productLinkField = value;
                this.RaisePropertyChanged("productLink");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string hsCode {
            get {
                return this.hsCodeField;
            }
            set {
                this.hsCodeField = value;
                this.RaisePropertyChanged("hsCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string hsGoodsName {
            get {
                return this.hsGoodsNameField;
            }
            set {
                this.hsGoodsNameField = value;
                this.RaisePropertyChanged("hsGoodsName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string originCountry {
            get {
                return this.originCountryField;
            }
            set {
                this.originCountryField = value;
                this.RaisePropertyChanged("originCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
                this.RaisePropertyChanged("brand");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string specificationsAndModels {
            get {
                return this.specificationsAndModelsField;
            }
            set {
                this.specificationsAndModelsField = value;
                this.RaisePropertyChanged("specificationsAndModels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string goodTaxCode {
            get {
                return this.goodTaxCodeField;
            }
            set {
                this.goodTaxCodeField = value;
                this.RaisePropertyChanged("goodTaxCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string applyEnterpriseCode {
            get {
                return this.applyEnterpriseCodeField;
            }
            set {
                this.applyEnterpriseCodeField = value;
                this.RaisePropertyChanged("applyEnterpriseCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string applyEnterpriseCodeCIQ {
            get {
                return this.applyEnterpriseCodeCIQField;
            }
            set {
                this.applyEnterpriseCodeCIQField = value;
                this.RaisePropertyChanged("applyEnterpriseCodeCIQ");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createProduct", WrapperNamespace="http://www.example.org/ServiceForProduct/", IsWrapped=true)]
    public partial class createProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.ProductReport.HeaderRequest HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.ProductReport.ProductInfo ProductInfo;
        
        public createProductRequest() {
        }
        
        public createProductRequest(pbxdata.web.ProductReport.HeaderRequest HeaderRequest, pbxdata.web.ProductReport.ProductInfo ProductInfo) {
            this.HeaderRequest = HeaderRequest;
            this.ProductInfo = ProductInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createProductResponse", WrapperNamespace="http://www.example.org/ServiceForProduct/", IsWrapped=true)]
    public partial class createProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ask;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.ProductReport.errorType[] error;
        
        public createProductResponse() {
        }
        
        public createProductResponse(string ask, string message, pbxdata.web.ProductReport.errorType[] error) {
            this.ask = ask;
            this.message = message;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProduct", WrapperNamespace="http://www.example.org/ServiceForProduct/", IsWrapped=true)]
    public partial class getProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.ProductReport.HeaderRequest HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string productSku;
        
        public getProductRequest() {
        }
        
        public getProductRequest(pbxdata.web.ProductReport.HeaderRequest HeaderRequest, string productSku) {
            this.HeaderRequest = HeaderRequest;
            this.productSku = productSku;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getProductResponse", WrapperNamespace="http://www.example.org/ServiceForProduct/", IsWrapped=true)]
    public partial class getProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ask;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.ProductReport.productData[] data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForProduct/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.ProductReport.errorType[] error;
        
        public getProductResponse() {
        }
        
        public getProductResponse(string ask, pbxdata.web.ProductReport.productData[] data, pbxdata.web.ProductReport.errorType[] error) {
            this.ask = ask;
            this.data = data;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceForProductChannel : pbxdata.web.ProductReport.ServiceForProduct, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceForProductClient : System.ServiceModel.ClientBase<pbxdata.web.ProductReport.ServiceForProduct>, pbxdata.web.ProductReport.ServiceForProduct {
        
        public ServiceForProductClient() {
        }
        
        public ServiceForProductClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceForProductClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceForProductClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceForProductClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pbxdata.web.ProductReport.createProductResponse pbxdata.web.ProductReport.ServiceForProduct.createProduct(pbxdata.web.ProductReport.createProductRequest request) {
            return base.Channel.createProduct(request);
        }
        
        public string createProduct(pbxdata.web.ProductReport.HeaderRequest HeaderRequest, pbxdata.web.ProductReport.ProductInfo ProductInfo, out string message, out pbxdata.web.ProductReport.errorType[] error) {
            pbxdata.web.ProductReport.createProductRequest inValue = new pbxdata.web.ProductReport.createProductRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.ProductInfo = ProductInfo;
            pbxdata.web.ProductReport.createProductResponse retVal = ((pbxdata.web.ProductReport.ServiceForProduct)(this)).createProduct(inValue);
            message = retVal.message;
            error = retVal.error;
            return retVal.ask;
        }
        
        public System.Threading.Tasks.Task<pbxdata.web.ProductReport.createProductResponse> createProductAsync(pbxdata.web.ProductReport.createProductRequest request) {
            return base.Channel.createProductAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pbxdata.web.ProductReport.getProductResponse pbxdata.web.ProductReport.ServiceForProduct.getProduct(pbxdata.web.ProductReport.getProductRequest request) {
            return base.Channel.getProduct(request);
        }
        
        public string getProduct(pbxdata.web.ProductReport.HeaderRequest HeaderRequest, string productSku, out pbxdata.web.ProductReport.productData[] data, out pbxdata.web.ProductReport.errorType[] error) {
            pbxdata.web.ProductReport.getProductRequest inValue = new pbxdata.web.ProductReport.getProductRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.productSku = productSku;
            pbxdata.web.ProductReport.getProductResponse retVal = ((pbxdata.web.ProductReport.ServiceForProduct)(this)).getProduct(inValue);
            data = retVal.data;
            error = retVal.error;
            return retVal.ask;
        }
        
        public System.Threading.Tasks.Task<pbxdata.web.ProductReport.getProductResponse> getProductAsync(pbxdata.web.ProductReport.getProductRequest request) {
            return base.Channel.getProductAsync(request);
        }
    }
}
