//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace pbxdata.web.OrderReport {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/ServiceForOrder/", ConfigurationName="OrderReport.ServiceForOrder")]
    public interface ServiceForOrder {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/createOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pbxdata.web.OrderReport.createOrderResponse createOrder(pbxdata.web.OrderReport.createOrderRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/createOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<pbxdata.web.OrderReport.createOrderResponse> createOrderAsync(pbxdata.web.OrderReport.createOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/updateOrderStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pbxdata.web.OrderReport.updateOrderStatusResponse updateOrderStatus(pbxdata.web.OrderReport.updateOrderStatusRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/updateOrderStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<pbxdata.web.OrderReport.updateOrderStatusResponse> updateOrderStatusAsync(pbxdata.web.OrderReport.updateOrderStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/getOrderByCode", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pbxdata.web.OrderReport.getOrderByCodeResponse getOrderByCode(pbxdata.web.OrderReport.getOrderByCodeRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/getOrderByCode", ReplyAction="*")]
        System.Threading.Tasks.Task<pbxdata.web.OrderReport.getOrderByCodeResponse> getOrderByCodeAsync(pbxdata.web.OrderReport.getOrderByCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/createOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        pbxdata.web.OrderReport.updateOrderResponse updateOrder(pbxdata.web.OrderReport.updateOrderRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://www.example.org/ServiceForOrder/createOrder", ReplyAction="*")]
        System.Threading.Tasks.Task<pbxdata.web.OrderReport.updateOrderResponse> updateOrderAsync(pbxdata.web.OrderReport.updateOrderRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class HeaderRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string customerCodeField;
        
        private string appTokenField;
        
        private string appKeyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string customerCode {
            get {
                return this.customerCodeField;
            }
            set {
                this.customerCodeField = value;
                this.RaisePropertyChanged("customerCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string appToken {
            get {
                return this.appTokenField;
            }
            set {
                this.appTokenField = value;
                this.RaisePropertyChanged("appToken");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string appKey {
            get {
                return this.appKeyField;
            }
            set {
                this.appKeyField = value;
                this.RaisePropertyChanged("appKey");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class UpdateOrderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderCodeField;
        
        private string oabCountryField;
        
        private string oabStateNameField;
        
        private string oabCityField;
        
        private string smCodeField;
        
        private string referenceNoField;
        
        private string oabNameField;
        
        private string oabCompanyField;
        
        private string oabPostcodeField;
        
        private string oabStreetAddress1Field;
        
        private string oabStreetAddress2Field;
        
        private string oabPhoneField;
        
        private string oabEmailField;
        
        private string grossWtField;
        
        private string netWtField;
        
        private string currencyCodeField;
        
        private string chargeField;
        
        private string idTypeField;
        
        private string idNumberField;
        
        private string remarkField;
        
        private int orderStatusField;
        
        private bool orderStatusFieldSpecified;
        
        private productDeatilType[] orderProductField;
        
        private string deliveryFeeField;
        
        private string trackingNumberInField;
        
        private string serviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderCode {
            get {
                return this.orderCodeField;
            }
            set {
                this.orderCodeField = value;
                this.RaisePropertyChanged("orderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string oabCountry {
            get {
                return this.oabCountryField;
            }
            set {
                this.oabCountryField = value;
                this.RaisePropertyChanged("oabCountry");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string oabStateName {
            get {
                return this.oabStateNameField;
            }
            set {
                this.oabStateNameField = value;
                this.RaisePropertyChanged("oabStateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string oabCity {
            get {
                return this.oabCityField;
            }
            set {
                this.oabCityField = value;
                this.RaisePropertyChanged("oabCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string smCode {
            get {
                return this.smCodeField;
            }
            set {
                this.smCodeField = value;
                this.RaisePropertyChanged("smCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string oabName {
            get {
                return this.oabNameField;
            }
            set {
                this.oabNameField = value;
                this.RaisePropertyChanged("oabName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string oabCompany {
            get {
                return this.oabCompanyField;
            }
            set {
                this.oabCompanyField = value;
                this.RaisePropertyChanged("oabCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string oabPostcode {
            get {
                return this.oabPostcodeField;
            }
            set {
                this.oabPostcodeField = value;
                this.RaisePropertyChanged("oabPostcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string oabStreetAddress1 {
            get {
                return this.oabStreetAddress1Field;
            }
            set {
                this.oabStreetAddress1Field = value;
                this.RaisePropertyChanged("oabStreetAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string oabStreetAddress2 {
            get {
                return this.oabStreetAddress2Field;
            }
            set {
                this.oabStreetAddress2Field = value;
                this.RaisePropertyChanged("oabStreetAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string oabPhone {
            get {
                return this.oabPhoneField;
            }
            set {
                this.oabPhoneField = value;
                this.RaisePropertyChanged("oabPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string oabEmail {
            get {
                return this.oabEmailField;
            }
            set {
                this.oabEmailField = value;
                this.RaisePropertyChanged("oabEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string grossWt {
            get {
                return this.grossWtField;
            }
            set {
                this.grossWtField = value;
                this.RaisePropertyChanged("grossWt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string netWt {
            get {
                return this.netWtField;
            }
            set {
                this.netWtField = value;
                this.RaisePropertyChanged("netWt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string charge {
            get {
                return this.chargeField;
            }
            set {
                this.chargeField = value;
                this.RaisePropertyChanged("charge");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
                this.RaisePropertyChanged("idType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
                this.RaisePropertyChanged("idNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public int orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool orderStatusSpecified {
            get {
                return this.orderStatusFieldSpecified;
            }
            set {
                this.orderStatusFieldSpecified = value;
                this.RaisePropertyChanged("orderStatusSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("orderProduct", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public productDeatilType[] orderProduct {
            get {
                return this.orderProductField;
            }
            set {
                this.orderProductField = value;
                this.RaisePropertyChanged("orderProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string deliveryFee {
            get {
                return this.deliveryFeeField;
            }
            set {
                this.deliveryFeeField = value;
                this.RaisePropertyChanged("deliveryFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string trackingNumberIn {
            get {
                return this.trackingNumberInField;
            }
            set {
                this.trackingNumberInField = value;
                this.RaisePropertyChanged("trackingNumberIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class productDeatilType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productSkuField;
        
        private float[] transactionPriceField;
        
        private float[] dealPriceField;
        
        private int opQuantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string productSku {
            get {
                return this.productSkuField;
            }
            set {
                this.productSkuField = value;
                this.RaisePropertyChanged("productSku");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("transactionPrice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public float[] transactionPrice {
            get {
                return this.transactionPriceField;
            }
            set {
                this.transactionPriceField = value;
                this.RaisePropertyChanged("transactionPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dealPrice", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public float[] dealPrice {
            get {
                return this.dealPriceField;
            }
            set {
                this.dealPriceField = value;
                this.RaisePropertyChanged("dealPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int opQuantity {
            get {
                return this.opQuantityField;
            }
            set {
                this.opQuantityField = value;
                this.RaisePropertyChanged("opQuantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class OrderDetailType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string skuNoField;
        
        private string skuNameField;
        
        private string skuCnNameField;
        
        private string quantityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string skuNo {
            get {
                return this.skuNoField;
            }
            set {
                this.skuNoField = value;
                this.RaisePropertyChanged("skuNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string skuName {
            get {
                return this.skuNameField;
            }
            set {
                this.skuNameField = value;
                this.RaisePropertyChanged("skuName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string skuCnName {
            get {
                return this.skuCnNameField;
            }
            set {
                this.skuCnNameField = value;
                this.RaisePropertyChanged("skuCnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("quantity");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class OrderData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string orderCodeField;
        
        private string smCodeField;
        
        private string orderStatusField;
        
        private string customsStatusField;
        
        private string countryNameField;
        
        private string provinceNameField;
        
        private string referenceNoField;
        
        private string trackingNumberField;
        
        private string trackingNumberInField;
        
        private string consigneeNameField;
        
        private string consigneeCompanyField;
        
        private string consigneePostcodeField;
        
        private string consigneeAddress1Field;
        
        private string consigneeAddress2Field;
        
        private string consigneePhoneField;
        
        private string consigneeEmailField;
        
        private string grossWtField;
        
        private string netWtField;
        
        private string currencyCodeField;
        
        private string idTypeField;
        
        private string idNumberField;
        
        private string remarkField;
        
        private string deliveryFeeField;
        
        private OrderDetailType[] orderDetailTypeField;
        
        private string serviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string orderCode {
            get {
                return this.orderCodeField;
            }
            set {
                this.orderCodeField = value;
                this.RaisePropertyChanged("orderCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string smCode {
            get {
                return this.smCodeField;
            }
            set {
                this.smCodeField = value;
                this.RaisePropertyChanged("smCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string customsStatus {
            get {
                return this.customsStatusField;
            }
            set {
                this.customsStatusField = value;
                this.RaisePropertyChanged("customsStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string countryName {
            get {
                return this.countryNameField;
            }
            set {
                this.countryNameField = value;
                this.RaisePropertyChanged("countryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string provinceName {
            get {
                return this.provinceNameField;
            }
            set {
                this.provinceNameField = value;
                this.RaisePropertyChanged("provinceName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("trackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string trackingNumberIn {
            get {
                return this.trackingNumberInField;
            }
            set {
                this.trackingNumberInField = value;
                this.RaisePropertyChanged("trackingNumberIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string consigneeName {
            get {
                return this.consigneeNameField;
            }
            set {
                this.consigneeNameField = value;
                this.RaisePropertyChanged("consigneeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string consigneeCompany {
            get {
                return this.consigneeCompanyField;
            }
            set {
                this.consigneeCompanyField = value;
                this.RaisePropertyChanged("consigneeCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string consigneePostcode {
            get {
                return this.consigneePostcodeField;
            }
            set {
                this.consigneePostcodeField = value;
                this.RaisePropertyChanged("consigneePostcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string consigneeAddress1 {
            get {
                return this.consigneeAddress1Field;
            }
            set {
                this.consigneeAddress1Field = value;
                this.RaisePropertyChanged("consigneeAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string consigneeAddress2 {
            get {
                return this.consigneeAddress2Field;
            }
            set {
                this.consigneeAddress2Field = value;
                this.RaisePropertyChanged("consigneeAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string consigneePhone {
            get {
                return this.consigneePhoneField;
            }
            set {
                this.consigneePhoneField = value;
                this.RaisePropertyChanged("consigneePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string consigneeEmail {
            get {
                return this.consigneeEmailField;
            }
            set {
                this.consigneeEmailField = value;
                this.RaisePropertyChanged("consigneeEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string grossWt {
            get {
                return this.grossWtField;
            }
            set {
                this.grossWtField = value;
                this.RaisePropertyChanged("grossWt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string netWt {
            get {
                return this.netWtField;
            }
            set {
                this.netWtField = value;
                this.RaisePropertyChanged("netWt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
                this.RaisePropertyChanged("idType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
                this.RaisePropertyChanged("idNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string deliveryFee {
            get {
                return this.deliveryFeeField;
            }
            set {
                this.deliveryFeeField = value;
                this.RaisePropertyChanged("deliveryFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("OrderDetailType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public OrderDetailType[] OrderDetailType {
            get {
                return this.orderDetailTypeField;
            }
            set {
                this.orderDetailTypeField = value;
                this.RaisePropertyChanged("OrderDetailType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=24)]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class errorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string errorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("errorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.example.org/ServiceForOrder/")]
    public partial class OrderInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string oabCountyField;
        
        private string oabStateNameField;
        
        private string oabCityField;
        
        private string smCodeField;
        
        private string referenceNoField;
        
        private string oabNameField;
        
        private string oabCompanyField;
        
        private string oabPostcodeField;
        
        private string oabStreetAddress1Field;
        
        private string oabStreetAddress2Field;
        
        private string oabPhoneField;
        
        private string oabEmailField;
        
        private string grossWtField;
        
        private string netWtField;
        
        private string currencyCodeField;
        
        private string idTypeField;
        
        private string idNumberField;
        
        private string remarkField;
        
        private string orderStatusField;
        
        private productDeatilType[] orderProductField;
        
        private string deliveryFeeField;
        
        private string trackingNumberField;
        
        private string trackingNumberInField;
        
        private string serviceTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string oabCounty {
            get {
                return this.oabCountyField;
            }
            set {
                this.oabCountyField = value;
                this.RaisePropertyChanged("oabCounty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string oabStateName {
            get {
                return this.oabStateNameField;
            }
            set {
                this.oabStateNameField = value;
                this.RaisePropertyChanged("oabStateName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string oabCity {
            get {
                return this.oabCityField;
            }
            set {
                this.oabCityField = value;
                this.RaisePropertyChanged("oabCity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string smCode {
            get {
                return this.smCodeField;
            }
            set {
                this.smCodeField = value;
                this.RaisePropertyChanged("smCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string referenceNo {
            get {
                return this.referenceNoField;
            }
            set {
                this.referenceNoField = value;
                this.RaisePropertyChanged("referenceNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string oabName {
            get {
                return this.oabNameField;
            }
            set {
                this.oabNameField = value;
                this.RaisePropertyChanged("oabName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string oabCompany {
            get {
                return this.oabCompanyField;
            }
            set {
                this.oabCompanyField = value;
                this.RaisePropertyChanged("oabCompany");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string oabPostcode {
            get {
                return this.oabPostcodeField;
            }
            set {
                this.oabPostcodeField = value;
                this.RaisePropertyChanged("oabPostcode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string oabStreetAddress1 {
            get {
                return this.oabStreetAddress1Field;
            }
            set {
                this.oabStreetAddress1Field = value;
                this.RaisePropertyChanged("oabStreetAddress1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string oabStreetAddress2 {
            get {
                return this.oabStreetAddress2Field;
            }
            set {
                this.oabStreetAddress2Field = value;
                this.RaisePropertyChanged("oabStreetAddress2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string oabPhone {
            get {
                return this.oabPhoneField;
            }
            set {
                this.oabPhoneField = value;
                this.RaisePropertyChanged("oabPhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string oabEmail {
            get {
                return this.oabEmailField;
            }
            set {
                this.oabEmailField = value;
                this.RaisePropertyChanged("oabEmail");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string grossWt {
            get {
                return this.grossWtField;
            }
            set {
                this.grossWtField = value;
                this.RaisePropertyChanged("grossWt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string netWt {
            get {
                return this.netWtField;
            }
            set {
                this.netWtField = value;
                this.RaisePropertyChanged("netWt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public string idType {
            get {
                return this.idTypeField;
            }
            set {
                this.idTypeField = value;
                this.RaisePropertyChanged("idType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public string idNumber {
            get {
                return this.idNumberField;
            }
            set {
                this.idNumberField = value;
                this.RaisePropertyChanged("idNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public string remark {
            get {
                return this.remarkField;
            }
            set {
                this.remarkField = value;
                this.RaisePropertyChanged("remark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public string orderStatus {
            get {
                return this.orderStatusField;
            }
            set {
                this.orderStatusField = value;
                this.RaisePropertyChanged("orderStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("orderProduct", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public productDeatilType[] orderProduct {
            get {
                return this.orderProductField;
            }
            set {
                this.orderProductField = value;
                this.RaisePropertyChanged("orderProduct");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=20)]
        public string deliveryFee {
            get {
                return this.deliveryFeeField;
            }
            set {
                this.deliveryFeeField = value;
                this.RaisePropertyChanged("deliveryFee");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=21)]
        public string trackingNumber {
            get {
                return this.trackingNumberField;
            }
            set {
                this.trackingNumberField = value;
                this.RaisePropertyChanged("trackingNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=22)]
        public string trackingNumberIn {
            get {
                return this.trackingNumberInField;
            }
            set {
                this.trackingNumberInField = value;
                this.RaisePropertyChanged("trackingNumberIn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=23)]
        public string serviceType {
            get {
                return this.serviceTypeField;
            }
            set {
                this.serviceTypeField = value;
                this.RaisePropertyChanged("serviceType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrder", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class createOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.HeaderRequest HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.OrderInfo OrderInfo;
        
        public createOrderRequest() {
        }
        
        public createOrderRequest(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, pbxdata.web.OrderReport.OrderInfo OrderInfo) {
            this.HeaderRequest = HeaderRequest;
            this.OrderInfo = OrderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createOrderResponse", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class createOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ask;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.errorType[] error;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute("referenceNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.errorType[] referenceNo;
        
        public createOrderResponse() {
        }
        
        public createOrderResponse(string ask, string message, string orderCode, pbxdata.web.OrderReport.errorType[] error, pbxdata.web.OrderReport.errorType[] referenceNo) {
            this.ask = ask;
            this.message = message;
            this.orderCode = orderCode;
            this.error = error;
            this.referenceNo = referenceNo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOrderStatus", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class updateOrderStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.HeaderRequest HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int orderStatus;
        
        public updateOrderStatusRequest() {
        }
        
        public updateOrderStatusRequest(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, string orderCode, int orderStatus) {
            this.HeaderRequest = HeaderRequest;
            this.orderCode = orderCode;
            this.orderStatus = orderStatus;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOrderStatusResponse", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class updateOrderStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("ask", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] ask;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("message", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.errorType[] error;
        
        public updateOrderStatusResponse() {
        }
        
        public updateOrderStatusResponse(string[] ask, string orderCode, string[] message, pbxdata.web.OrderReport.errorType[] error) {
            this.ask = ask;
            this.orderCode = orderCode;
            this.message = message;
            this.error = error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrderByCode", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class getOrderByCodeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.HeaderRequest HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderCode;
        
        public getOrderByCodeRequest() {
        }
        
        public getOrderByCodeRequest(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, string orderCode) {
            this.HeaderRequest = HeaderRequest;
            this.orderCode = orderCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrderByCodeResponse", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class getOrderByCodeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ask;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("Data", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.OrderData[] Data;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute("Error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.errorType[] Error;
        
        public getOrderByCodeResponse() {
        }
        
        public getOrderByCodeResponse(string ask, pbxdata.web.OrderReport.OrderData[] Data, pbxdata.web.OrderReport.errorType[] Error) {
            this.ask = ask;
            this.Data = Data;
            this.Error = Error;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOrder", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class updateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.HeaderRequest HeaderRequest;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.UpdateOrderInfo OrderInfo;
        
        public updateOrderRequest() {
        }
        
        public updateOrderRequest(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, pbxdata.web.OrderReport.UpdateOrderInfo OrderInfo) {
            this.HeaderRequest = HeaderRequest;
            this.OrderInfo = OrderInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="updateOrderResponse", WrapperNamespace="http://www.example.org/ServiceForOrder/", IsWrapped=true)]
    public partial class updateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ask;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string orderCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.example.org/ServiceForOrder/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("error", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public pbxdata.web.OrderReport.errorType[] error;
        
        public updateOrderResponse() {
        }
        
        public updateOrderResponse(string ask, string message, string orderCode, pbxdata.web.OrderReport.errorType[] error) {
            this.ask = ask;
            this.message = message;
            this.orderCode = orderCode;
            this.error = error;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceForOrderChannel : pbxdata.web.OrderReport.ServiceForOrder, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceForOrderClient : System.ServiceModel.ClientBase<pbxdata.web.OrderReport.ServiceForOrder>, pbxdata.web.OrderReport.ServiceForOrder {
        
        public ServiceForOrderClient() {
        }
        
        public ServiceForOrderClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceForOrderClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceForOrderClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceForOrderClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pbxdata.web.OrderReport.createOrderResponse pbxdata.web.OrderReport.ServiceForOrder.createOrder(pbxdata.web.OrderReport.createOrderRequest request) {
            return base.Channel.createOrder(request);
        }
        
        public string createOrder(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, pbxdata.web.OrderReport.OrderInfo OrderInfo, out string message, out string orderCode, out pbxdata.web.OrderReport.errorType[] error, out pbxdata.web.OrderReport.errorType[] referenceNo) {
            pbxdata.web.OrderReport.createOrderRequest inValue = new pbxdata.web.OrderReport.createOrderRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.OrderInfo = OrderInfo;
            pbxdata.web.OrderReport.createOrderResponse retVal = ((pbxdata.web.OrderReport.ServiceForOrder)(this)).createOrder(inValue);
            message = retVal.message;
            orderCode = retVal.orderCode;
            error = retVal.error;
            referenceNo = retVal.referenceNo;
            return retVal.ask;
        }
        
        public System.Threading.Tasks.Task<pbxdata.web.OrderReport.createOrderResponse> createOrderAsync(pbxdata.web.OrderReport.createOrderRequest request) {
            return base.Channel.createOrderAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pbxdata.web.OrderReport.updateOrderStatusResponse pbxdata.web.OrderReport.ServiceForOrder.updateOrderStatus(pbxdata.web.OrderReport.updateOrderStatusRequest request) {
            return base.Channel.updateOrderStatus(request);
        }
        
        public string[] updateOrderStatus(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, ref string orderCode, int orderStatus, out string[] message, out pbxdata.web.OrderReport.errorType[] error) {
            pbxdata.web.OrderReport.updateOrderStatusRequest inValue = new pbxdata.web.OrderReport.updateOrderStatusRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.orderCode = orderCode;
            inValue.orderStatus = orderStatus;
            pbxdata.web.OrderReport.updateOrderStatusResponse retVal = ((pbxdata.web.OrderReport.ServiceForOrder)(this)).updateOrderStatus(inValue);
            orderCode = retVal.orderCode;
            message = retVal.message;
            error = retVal.error;
            return retVal.ask;
        }
        
        public System.Threading.Tasks.Task<pbxdata.web.OrderReport.updateOrderStatusResponse> updateOrderStatusAsync(pbxdata.web.OrderReport.updateOrderStatusRequest request) {
            return base.Channel.updateOrderStatusAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pbxdata.web.OrderReport.getOrderByCodeResponse pbxdata.web.OrderReport.ServiceForOrder.getOrderByCode(pbxdata.web.OrderReport.getOrderByCodeRequest request) {
            return base.Channel.getOrderByCode(request);
        }
        
        public string getOrderByCode(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, string orderCode, out pbxdata.web.OrderReport.OrderData[] Data, out pbxdata.web.OrderReport.errorType[] Error) {
            pbxdata.web.OrderReport.getOrderByCodeRequest inValue = new pbxdata.web.OrderReport.getOrderByCodeRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.orderCode = orderCode;
            pbxdata.web.OrderReport.getOrderByCodeResponse retVal = ((pbxdata.web.OrderReport.ServiceForOrder)(this)).getOrderByCode(inValue);
            Data = retVal.Data;
            Error = retVal.Error;
            return retVal.ask;
        }
        
        public System.Threading.Tasks.Task<pbxdata.web.OrderReport.getOrderByCodeResponse> getOrderByCodeAsync(pbxdata.web.OrderReport.getOrderByCodeRequest request) {
            return base.Channel.getOrderByCodeAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        pbxdata.web.OrderReport.updateOrderResponse pbxdata.web.OrderReport.ServiceForOrder.updateOrder(pbxdata.web.OrderReport.updateOrderRequest request) {
            return base.Channel.updateOrder(request);
        }
        
        public string updateOrder(pbxdata.web.OrderReport.HeaderRequest HeaderRequest, pbxdata.web.OrderReport.UpdateOrderInfo OrderInfo, out string message, out string orderCode, out pbxdata.web.OrderReport.errorType[] error) {
            pbxdata.web.OrderReport.updateOrderRequest inValue = new pbxdata.web.OrderReport.updateOrderRequest();
            inValue.HeaderRequest = HeaderRequest;
            inValue.OrderInfo = OrderInfo;
            pbxdata.web.OrderReport.updateOrderResponse retVal = ((pbxdata.web.OrderReport.ServiceForOrder)(this)).updateOrder(inValue);
            message = retVal.message;
            orderCode = retVal.orderCode;
            error = retVal.error;
            return retVal.ask;
        }
        
        public System.Threading.Tasks.Task<pbxdata.web.OrderReport.updateOrderResponse> updateOrderAsync(pbxdata.web.OrderReport.updateOrderRequest request) {
            return base.Channel.updateOrderAsync(request);
        }
    }
}
